### ISSUE TITLE
Android demo project?

### ISSUE THREAD

**Issue by dragen1860** [zetyquickly/DensePoseFnL#1]
Dear author:
   It's really cool to make it possible to run on mobile device. Congratulations!
   I am also watching this area. However, lots of researcher like me are not familar with mobile development. We can export the caffe2 model, but unfortunately, we can not test it on mobile device. I noticed you have tested the lite densepose model on ARM cpu, Could you kindly share the android demo project? 
  Thank you very much!

**Comment by zetyquickly** [comment]
Hi, 

It is possible to run Caffe2 model on device using `speed_benchmark` binary. You can get it several ways, for example:
* from QNNPACK https://github.com/pytorch/QNNPACK#armv7-32-bit-android
* from PyTorch https://pytorch.org/mobile/android/#building-pytorch-android-from-source
