### ISSUE TITLE
Detectron2 version set to 0.1.1 after going to the specific commit as specified in the readme.

### ISSUE THREAD

**Issue by abhaydoke09** [zetyquickly/DensePoseFnL#13]
Hello Author,

Comment in this issue (https://github.com/zetyquickly/DensePoseFnL/issues/3#issuecomment-660464048) says that the detectron2 version should 0.1.0.

But when I build the detectron2 after doing "git checkout b1fe5127e41b506cd3769180ad774dec0bfd56b0" as per readme instructions in your repo, detectron2 version is automatically set 0.1.1

Can you please share the information about different library versions your setup is having? Is it okay to have dectectron2 version = 0.1.1?

Without the proper detectron2 version as well as other dependencies,  paper results are not being reproduced.

Looking forward to your kind response.

Thank you.

**Comment by zetyquickly** [comment]
Yes, it is needed to checkout on specifix commit before 0.1.1 of detectron2. Because the latter introduced some breaking changes to our project

**Comment by zetyquickly** [comment]
This issue might be stale because of new code version
