### ISSUE TITLE
Cannot import geffnet!

### ISSUE THREAD

**Issue by favorxin** [zetyquickly/DensePoseFnL#14]
Hello! I have a lot of interest in how to make densepose faster and lighter. It's meaningful. But it appears that there has been a mistake when I try to run your code. The modeling dir doesn't have geffnet.py file when I import geffnet. As shown in the following pic:

![image](https://user-images.githubusercontent.com/31987475/135089041-2a669263-272d-4e89-b961-e11cd8546aef.png)

I can inference the densepose in detectron2. And the running code is as following:  
`python apply_net.py show ./configs/densepose_rcnn_R_50_FPN_s1x.yaml ./R_50_FPN_s1x.pkl ./face1.png dp_contour --output ./saved_1.png`

I am looking forward to your replay! Thanks a lot!

**Comment by zetyquickly** [comment]
Hi @favorxin 

You're not the first :) I should update this repo already

Comment out geffnet import, because it's not used.

To inference our code use ```python train_net.py --config-file configs/s0_bv2_bifpn_f64_s3x.yaml --eval-only MODEL.WEIGHTS model.pth 
MODEL.RPN.POST_NMS_TOPK_TEST 100 MODEL.ROI_HEADS.NMS_THRESH_TEST 0.3```

But you need to get trained weights first. We won't provide it because of agreements

**Comment by zetyquickly** [comment]
https://github.com/zetyquickly/DensePoseFnL/issues/8#issuecomment-799630583
