### ISSUE TITLE
Mobile-RCNN (A) BiFPN yaml?

### ISSUE THREAD

**Issue by dragen1860** [zetyquickly/DensePoseFnL#2]
Dear authors: 
   Thank you again.
    Could you kindly share the Mobile-RCNN (A) BiFPN yaml configs? ~~

**Comment by rakhimovv** [comment]
Check this one `configs/densepose_parsing_rcnn_spnasnet_100_FPN_s3x.yaml`. Actually this is a version trained 3 times more iterations. We did not mention it in a paper.

**Comment by dragen1860** [comment]
@rakhimovv simply change the backbone to `BiFPN` to get BiFPN version?

**Comment by rakhimovv** [comment]
@dragen1860 yes
