### ISSUE TITLE
Inference Issue

### ISSUE THREAD

**Issue by andyzihaozhang** [zetyquickly/DensePoseFnL#3]
Dear author,

When I try to inference with the following command `python apply_net.py show configs/densepose_rcnn_R_50_FPN_s1x.yaml densepose_rcnn_R_50_FPN_s1x.pkl image.jpg dp_contour,bbox --output image_densepose_contour.png` as provided in the instruction. I received following error:

`Traceback (most recent call last):
  File "apply_net.py", line 321, in <module>
    main()
  File "apply_net.py", line 317, in main
    args.func(args)
  File "apply_net.py", line 74, in execute
    predictor = DefaultPredictor(cfg)
  File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 182, in __init__
    self.model = build_model(self.cfg)
  File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/modeling/meta_arch/build.py", line 21, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/config/config.py", line 147, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/config/config.py", line 180, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 79, in from_config
    "roi_heads": build_roi_heads(cfg, backbone.output_shape()),
  File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads
    return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
  File "/Users/zihaozhang/Desktop/Python Project/Intern/DensePoseFnL/densepose/roi_head.py", line 30, in __init__
    self._init_densepose_head(cfg)
  File "/Users/zihaozhang/Desktop/Python Project/Intern/DensePoseFnL/densepose/roi_head.py", line 39, in _init_densepose_head
    dp_pooler_scales = tuple(1.0 / self.feature_strides[k] for k in self.in_features)
  File "/Users/zihaozhang/Desktop/Python Project/Intern/DensePoseFnL/densepose/roi_head.py", line 39, in <genexpr>
    dp_pooler_scales = tuple(1.0 / self.feature_strides[k] for k in self.in_features)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'DensePoseROIHeads' object has no attribute 'feature_strides'`

I checked the code in densepose/roi_head.py and there is no self.feature_strides defined before usage.

Did I miss anything? Please help. Thank you!

**Comment by zetyquickly** [comment]
Please, specify which detectron2 version do you use?

**Comment by andyzihaozhang** [comment]
Thank you for your quick response!

I used the instruction in the [official repo](https://github.com/facebookresearch/detectron2).
The command I used is `python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'`
The version should be their newest release v0.2.

**Comment by zetyquickly** [comment]
Try to install `detectron2==0.1.0`

**Comment by QiyaoWei** [comment]
Dear author,

I am encountering this problem as well. Could you specify the instructions to install detectron2==0.1.0? I have tried cloning the detectron2 github repo, and running python -m pip install -e detectron2==0.1.0 as required by the original detectron2 repo, but received an error about detectron2==0.1.0 not being a valid requirement. Any help would be appreciated. Thanks!

**Comment by zetyquickly** [comment]
> Dear author,
> 
> I am encountering this problem as well. Could you specify the instructions to install detectron2==0.1.0? I have tried cloning the detectron2 github repo, and running python -m pip install -e detectron2==0.1.0 as required by the original detectron2 repo, but received an error about detectron2==0.1.0 not being a valid requirement. Any help would be appreciated. Thanks!

Hello @QiyaoWei 

We've revealed that this project depends on a specific commit od detectron2. To install it follow the steps described in updated README

**Comment by zetyquickly** [comment]
> Dear author,
> 
> When I try to inference with the following command `python apply_net.py show configs/densepose_rcnn_R_50_FPN_s1x.yaml densepose_rcnn_R_50_FPN_s1x.pkl image.jpg dp_contour,bbox --output image_densepose_contour.png` as provided in the instruction. I received following error:
> 
> `Traceback (most recent call last): File "apply_net.py", line 321, in <module> main() File "apply_net.py", line 317, in main args.func(args) File "apply_net.py", line 74, in execute predictor = DefaultPredictor(cfg) File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 182, in __init__ self.model = build_model(self.cfg) File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/modeling/meta_arch/build.py", line 21, in build_model model = META_ARCH_REGISTRY.get(meta_arch)(cfg) File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/config/config.py", line 147, in wrapped explicit_args = _get_args_from_config(from_config_func, *args, **kwargs) File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/config/config.py", line 180, in _get_args_from_config ret = from_config_func(*args, **kwargs) File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 79, in from_config "roi_heads": build_roi_heads(cfg, backbone.output_shape()), File "/opt/anaconda3/lib/python3.7/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape) File "/Users/zihaozhang/Desktop/Python Project/Intern/DensePoseFnL/densepose/roi_head.py", line 30, in __init__ self._init_densepose_head(cfg) File "/Users/zihaozhang/Desktop/Python Project/Intern/DensePoseFnL/densepose/roi_head.py", line 39, in _init_densepose_head dp_pooler_scales = tuple(1.0 / self.feature_strides[k] for k in self.in_features) File "/Users/zihaozhang/Desktop/Python Project/Intern/DensePoseFnL/densepose/roi_head.py", line 39, in <genexpr> dp_pooler_scales = tuple(1.0 / self.feature_strides[k] for k in self.in_features) File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__ type(self).__name__, name)) AttributeError: 'DensePoseROIHeads' object has no attribute 'feature_strides'`
> 
> I checked the code in densepose/roi_head.py and there is no self.feature_strides defined before usage.
> 
> Did I miss anything? Please help. Thank you!

Hello, @andyzihaozhang 

In addition to the above I want to mention that I've checked that `apply_net.py` script works with `s0_bv2_bifpn_f64_s3x.yaml` model.

**Comment by abhaydoke09** [comment]
> ry to install `detectron2==0.1.0`

@zetyquickly are there any instructions to install detectron2==0.1.0? 

I am unable to reproduce results in detectron2 v0.3. 

Can you please share instructions to install detectron2==0.1.0?
