### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by QiyaoWei** [zetyquickly/DensePoseFnL#4]
Dear author,

I have noticed that some .yaml files in "configs" folder correspond to the models in detectron2-densepose-modelzoo (such as the FPN ones), but I cannot find the Mobile-RCNN or Parsing-RCNN models anywhere. Is there a pretrained model for those .yaml scripts (such as "densepose_parsing_rcnn_R_50_FPN_s1x.yaml")? Thanks!

**Comment by zetyquickly** [comment]
Hi, @QiaoWei,

This configs are used to train a model from scratch. You can train your own model with them.

Densepose parsing RCNN R50 uses pretrained ResNet50 and other parsing configs uses pretrained efficientnet as a backbone. It comes with timm library.
