### ISSUE TITLE
Trained models

### ISSUE THREAD

**Issue by OValery16** [zetyquickly/DensePoseFnL#6]
Thanks for this brilliant piece of work.

For reproducibility purpose, can you provide your training weights ? (in https://github.com/zetyquickly/DensePoseFnL/blob/master/doc/OUR_MODEL_ZOO.md, there is not link to download them)

**Comment by zetyquickly** [comment]
Hello, @OValery16 
I am sorry but we can not due to legal obligations.

But it is possible for us to provide precise instructions if something is unclear in training repro

**Comment by rakhimovv** [comment]
@OValery16 in case it is still relevant, check out the recent changes, we added weights
