### ISSUE TITLE
Is densepose_rcnn_mobilenetv3_rw_FPN_s1x.yaml corresponding to MobileNetV3-Large-1.0 or MobileNetV3-Large-0.75?

### ISSUE THREAD

**Issue by abhaydoke09** [zetyquickly/DensePoseFnL#9]
densepose_rcnn_mobilenetv3_rw_FPN_s1x.yaml uses mobilenetv3_rw as backbone. Does mobilenetv3_rw mean MobileNetV3-Large-1.0 or MobileNetV3-Large-0.75 or MobileNetV3-Large-1.0 (minimal)?

Paper: https://arxiv.org/pdf/2006.15190.pdf (Table 2), does not mention anything about MobilenetV3_rw backbone.

Thank you.

**Comment by rakhimovv** [comment]
Hi, @abhaydoke09 ! mobilenetv3_rw corresponds to custom implementation of mobilenetv3 from Ross Wightman. Those numbers in the paper correspond to specific versions of mobilenetv3 which you can find here https://github.com/rwightman/gen-efficientnet-pytorch/blob/master/geffnet/mobilenetv3.py (with `tf_` prefix). We did not put all specific configs for every backbone model, but you can easily change backbone name in the config

**Comment by abhaydoke09** [comment]
Thank you @rakhimovv
